### ISSUE TITLE
JDK 23 support

### ISSUE THREAD

**Issue by Andre601** [xMrAfonso/BetterJDocs#3]
JDK 23 changed quite a bit in the Javadoc structure. While the most part of BetterJDocs seems unaffected by this change, are new components in the JDoc not properly formatted, resulting in these weird looking structures:
![grafik](https://github.com/user-attachments/assets/af3a61c3-1ec8-4df8-b4b3-7909fcc9fa13)

BetterJDocs should be updated to properly support the new JDocs structures.

**Comment by xMrAfonso** [comment]
Hey there, I have totally forgotten to update this. Not even Java 21 is fully supported yet. I will try my best to find some time to update this to Java 23 and below.

**Comment by Andre601** [comment]
No hurry. For the time being did I override parts of the JDOC css with the color scheme to at least have a dark themed JDoc
![grafik](https://github.com/user-attachments/assets/037d23d8-2bd4-458c-ae1b-a160b09ad2c3)

The CSS variables in case you're curious:
```css
:root {
    --body-text-color: #e0e0e3;
    --block-text-color: #949494;
    --body-background-color: #171717;
    --section-background-color: #1c1c1c;
    --detail-background-color: #212121;
    --navbar-background-color: #121212;
    --navbar-text-color: #ffffff;
    --subnav-background-color: #121212;
    --selected-background-color: #4186f5;
    --selected-text-color: #253441;
    --selected-link-color: #1f389c;
    --even-row-color: #212121;
    --odd-row-color: #1c1c1c;
    --title-color: #ffffff;
    --link-color: #a0c0f8;
    --link-color-active: #76a6f4;
    --snippet-background-color: #383838;
    --snippet-text-color: var(--block-text-color);
    --snippet-highlight-color: #f7c590;
    --border-color: #383838;
    --table-border-color: #000000;
    --search-input-background-color: #000000;
    --search-input-text-color: #ffffff;
    --search-input-placeholder-color: #909090;
    --search-tag-highlight-color: #ffff00;
    --copy-icon-brightness: 250%;
    --copy-button-background-color-active: rgba(168, 168, 176, 0.3);
    --invalid-tag-background-color: #ffe6e6;
    --invalid-tag-text-color: #000000;
}
```
